#### Rearrange an array such that arr[i] = i

In [1]:
import numpy as np

In [2]:
my_arr = [ -1, -1, 6, 1, 9, 3, 2, -1, 4, -1 ]

def Rearrange(arr):
    n = len(arr)

    for i in range(n):
        for j in range(n):
            if arr[j] == i:
                arr[i],arr[j] = arr[j],arr[i]
                
    return arr
            
Rearrange(my_arr)        
        

[-1, 1, 2, 3, 4, -1, 6, -1, -1, 9]

#### Write a program to reverse an array or string

In [3]:

Aitr = [1, 2, 3, 4, 5, 6, 7, 8]


#---------------// METHOD 1 -ITERATIVE WAY //------------------#

def reverseItr(arr):
    n = len(arr)
    print(n)
    for i in range(int(n/2)):
        start = i
        end = (n-1)-i
        
        arr[start], arr[end] = arr[end], arr[start]
    return arr

#reverseItr(A)

#---------------// METHOD 2 -RECURSIVE WAY //------------------#

Bitr = [1, 2, 3, 4, 5, 6, 7, 8]

def reverseRec(arr,start,end):
    if start >= end:
        return
    arr[start], arr[end] = arr[end], arr[start]
    reverseRec(arr,start+1,end-1)   
    return arr

reverseRec(Bitr,0,7)

[8, 7, 6, 5, 4, 3, 2, 1]

In [4]:
Bitr = [1, 2, 3, 4, 5, 6, 7, 8]

def reverseRec(arr,start,end):
    if start >= end:
        return
    arr[start], arr[end] = arr[end], arr[start]
    reverseRec(arr,start+1,end-1)         
    return arr
reverseRec(Bitr,0,7)

[8, 7, 6, 5, 4, 3, 2, 1]

#### Rearrange array such that arr[i] >= arr[j] if i is even and arr[i]<=arr[j] if i is odd and j < i

In [5]:
my_arr = [9,8,4,5,3,6,7,2,1]

def RearrangeEO(arr):
    
    n = len(arr)
    
    evenPos = int(n/2)
    oddPos = n- evenPos

    arr1 = arr.copy()
    arr1.sort()
    
    j = oddPos - 1

    for i in range(0, n, 2):
        arr[i] = arr1[j]
        j = j - 1
     
    j = oddPos
 
    for i in range(1, n, 2):
        arr[i] = arr1[j]
        j = j + 1
    
    return arr
    
RearrangeEO(my_arr)       

[5, 6, 4, 7, 3, 8, 2, 9, 1]

#### Move all zeroes to end of array

###### Method 1

In [6]:
my_Arr = np.array([0, 9, 8, 4, 0, 0, 2, 7, 0, 6, 0])

def PushZeroToEnd(arr):
    
    n = len(arr)
    
    p = 0
    
    for i in range(n):
        if arr[i] != 0:
            arr[p] = arr[i]
            p += 1
    
    while p<n:
        arr[p] = 0
        p+=1
    
    return arr
    
PushZeroToEnd(my_Arr)

array([9, 8, 4, 2, 7, 6, 0, 0, 0, 0, 0])

###### Method 2 Using single traversal

In [7]:
Array = np.array([0, 1, 9, 8, 4, 0, 0, 2, 7, 0, 6, 0, 9])

def STPushZeroEnds(arr):
    n = len(arr)
    
    count = 0
    for i in range(n):
        if arr[i] != 0:
            arr[count],arr[i] = arr[i],arr[count]
            count += 1
    return arr

STPushZeroEnds(Array)

array([1, 9, 8, 4, 2, 7, 6, 9, 0, 0, 0, 0, 0])

#### Minimum swaps required to bring all elements less than or equal to k together

In [8]:
def MinSwapK(arr,k):
    
    n = len(arr)
    
    #Counting how many total elements are there less than equal to K. (KLE = Elemetns less than K)
    KLE = 0
    for i in range(n):
        if arr[i] <= k:
            KLE += 1
            
    #Total elements Bigger than K in CURRENT WINDOW. (Swaps required, raw value to be refined)
    swaps = 0
    for j in range(KLE):
        if arr[j] > k:
            swaps += 1
        
    r = swaps
    s = KLE-1
    
    for i in range(n):
        if r == s:
            break
        
        if arr[i] > k:
            r -= 1
            
        if arr[s] > k:
            r += 1
            
        r = min(r,swaps)
        
        s+=1
        
    return print("Min swaps required are {}".format(r))

Array = np.array([2, 7, 9, 5, 8, 7, 4])

MinSwapK(Array, 5)
    

Min swaps required are 2


#### Rearrange positive and negative numbers using inbuilt sort function

In [9]:
#Counting total negative numbers
count = 0
for i in range(len(my_arr)):
    if my_arr[i] <0:
        count+=1
    

#Reverse Funcion

def reverse(array, start, end):
    while(start < end):
        temp = array[start]
        array[start] = array[end]
        array[end] = temp
        start += 1
        end -= 1

def rearrange(arr,start,end):
    
    #Exit condition if start = end
    if start == end:
        return
    
    #rearranging array (recursion) from first element of new array
    
    rearrange(arr,(start+1) , end)
    
    if arr[start] > 0:
        reverse(arr,start+1,end)
        reverse(arr,start ,end)
    
    return arr
       
my_arr = np.array([1,-4,2,6,9,-7,-5,44,445,-23,-2])

rearrange(my_arr,0,10)

array([ -4,  -7,  -5, -23,  -2, 445,  44,   9,   6,   2,   1])

#### Rearrange array such that even positioned are greater than odd

In [10]:
Array_kp = np.array([1, 9, 8, 4, 2, 7, 6, 5])

def arrange_EO(arr):
    n = len(arr)
    
    arr.sort()
    print("Sorted array",arr)
    
    ans = [0]*n
    p= 0
    q = n-1
    for i in range(n):
        
        #assign even positions with max values
        if (i+1) % 2 == 0:
            ans[i] = arr[q]
            q -= 1
        else:
            ans[i] = arr[p]
            p+=1
            
            
    return print("Rearranged array",ans)

    
    
    
arrange_EO(Array_kp)            

Sorted array [1 2 4 5 6 7 8 9]
Rearranged array [1, 9, 2, 8, 4, 7, 5, 6]


#### Set 1-  Rearrange an array in order – smallest, largest, 2nd smallest, 2nd largest, ..

In [11]:
Array_sl = np.array([1, 9, 3, 8, 4, 2, 7, 6,5,10,14,11,13,12])

def reArrange(arr):
    
    arr.sort()
    
    i = 0
    j = len(arr)-1
    
    ans = []*j
    
    while (i<=j):
        if i<j:
            ans.append(arr[i])
            ans.append(arr[j])
            i += 1
            j -= 1
        elif i==j:
            ans.append(arr[i])
            break

    return ans
    
reArrange(Array_sl)

[1, 14, 2, 13, 3, 12, 4, 11, 5, 10, 6, 9, 7, 8]

#### Double the first element and move zero to end

In [12]:
Array = np.array([0, 1, 9, 8, 4, 0, 0, 2, 7, 0, 6, 0, 9])

def STPushZeroEnds(arr):
    n = len(arr)
    
    for i in range(n):
        arr[i] = 2 * arr[i]
        
    count = 0
    for i in range(n):
        if arr[i] != 0:
            arr[count],arr[i] = arr[i],arr[count]
            count += 1
    return arr

STPushZeroEnds(Array)

array([ 2, 18, 16,  8,  4, 14, 12, 18,  0,  0,  0,  0,  0])


#### Reorder an array according to given indexes

In [13]:
array = np.array([50, 40, 70, 60, 90])
indexes = np.array([3, 0, 4, 1, 2])

def ArrangeIndexes(arr,ind):
    
    n =  len(arr)
    temp = np.array([0]*n)
    
    for i in range(n):
        p = ind[i]
        temp[p] = array[i]
    
    return temp

ArrangeIndexes(array,indexes)

array([40, 60, 90, 50, 70])

#### Rearrange positive and negative numbers with constant extra space

In [14]:
my_arr = np.array([1,4,-2,3,6,-9,8,-55,56,-44,-76])
end = len(my_arr)-1

def rotate(arr,start,end):
    
    while start < end:
        arr[start],arr[start+1] = arr[start+1],arr[start]
        start += 1

def reArrange(arr):
    
    #Total neg numbers present
    count = 0
    for i in range(len(arr)):
        if arr[i]<0:
            count += 1
    
    p=0
    k = 1
    while p<count:
        if arr[p] >= 0:
            rotate(arr,p,end)
            print("After Step {}".format(k),arr)
            k+=1
            if p<=0:
                p=0
            elif p>0:
                p-=1            
        else:
            p+=1
            
    return arr



reArrange(my_arr)

After Step 1 [  4  -2   3   6  -9   8 -55  56 -44 -76   1]
After Step 2 [ -2   3   6  -9   8 -55  56 -44 -76   1   4]
After Step 3 [ -2   6  -9   8 -55  56 -44 -76   1   4   3]
After Step 4 [ -2  -9   8 -55  56 -44 -76   1   4   3   6]
After Step 5 [ -2  -9 -55  56 -44 -76   1   4   3   6   8]
After Step 6 [ -2  -9 -55 -44 -76   1   4   3   6   8  56]


array([ -2,  -9, -55, -44, -76,   1,   4,   3,   6,   8,  56])

#### Arrange given numbers to form the biggest number | Set 1

In [15]:
my_Arr = np.array([1, 34, 3, 98, 9, 76, 45, 4])

def compare(arr):
    n=len(arr)
    ans = ""
    for j in range(n-1):
        for i in range(j,n-1):
            ab = str(arr[j]) + str(arr[i+1])
            ba = str(arr[i+1]) + str(arr[j])
            if int(ab) < int(ba):
                arr[j],arr[i+1] = arr[i+1],arr[j]                
    
    for k in range(n):
        ans = ans + str(arr[k])
    
    return print( "The biggest number can be formed is {}".format(ans))
        
compare(my_Arr)

The biggest number can be formed is 998764543431


#### Rearrange an array such that ‘arr[j]’ becomes ‘i’ if ‘arr[i]’ is ‘j’ | Set 1

In [16]:
array = np.array([2, 0, 1, 4, 5, 3])

def RearrangeJI(arr):
    n = len(arr)
    arr2 = arr.copy()
    for i in range(n):
        p = arr[i]
        arr2[p] = i
    return arr2

RearrangeJI(array)

array([1, 2, 0, 5, 3, 4])

#### Set 2-  Rearrange an array in order – smallest, largest, 2nd smallest, 2nd largest, ..

In [17]:
Array_s2 = np.array([7, 9, 3, 8, 4, 2, 6,5,10,1])

def RearrangeSL(arr):
    n = len(arr)
    j=0
    for i in range(n):
        if i%2 == 0:
            p = min(arr[j:n])
            for k in range(n):
                if arr[k] == p:
                    id = k
            arr[i],arr[id] = arr[id],arr[i]
            
        else:
            p = max(arr[j:n])
            for k in range(n):
                if arr[k] == p:
                    id = k
            arr[i],arr[id] = arr[id],arr[i]
                   
        
        j+=1 
    
    return arr       
            
RearrangeSL(Array_s2)        


array([ 1, 10,  2,  9,  3,  8,  4,  7,  5,  6])

#### Move all negative elements to end in order with extra space allowed

In [18]:
my_arr = np.array([1,4,-2,3,6,-9,8,98,-55,56])
end = len(my_arr)-1

def rotate(arr,start,end):
    
    while start < end:
        arr[start],arr[start+1] = arr[start+1],arr[start]
        start += 1

def reArrange(arr):
    
    #Total neg numbers present
    count = 0
    for i in range(len(arr)):
        if arr[i]>0:
            count += 1
    
    p=0
    k = 1
    while p<count:
        if arr[p] <= 0:
            rotate(arr,p,end)
            print("After Step {}".format(k),arr)
            k+=1
            
        else:
            p+=1
            
    return arr



reArrange(my_arr)

After Step 1 [  1   4   3   6  -9   8  98 -55  56  -2]
After Step 2 [  1   4   3   6   8  98 -55  56  -2  -9]
After Step 3 [  1   4   3   6   8  98  56  -2  -9 -55]


array([  1,   4,   3,   6,   8,  98,  56,  -2,  -9, -55])

#### Rearrange positive and negative numbers in O(n) time and O(1) extra space

#### Positive elements at even and negative at odd positions (Relative order not maintained)


In [19]:
import numpy as np                

def pivot(arr):
    n = len(arr)
    p=0
    for i in range(n):
        if pos>neg:
            if arr[i] < 0:
                arr[p],arr[i] = arr[i],arr[p]
                p+=1
        elif pos<=neg:
            if arr[i] > 0:
                arr[p],arr[i] = arr[i],arr[p]
                p+=1

            
    return arr

def PosNeg(arr):
    
    pivot(arr)
    print("pos, negs are",pos,neg)
    p = min(pos,neg)
    
    if p%2 != 0:
        p = p+1
    
    for i in range(int(p/2)):

        if p<n:
            arr[2*i+1],arr[p] =  arr[p],arr[2*i+1]
            p+=2
        else:
            break
    return arr

#//----------------------------------------------------------------//

my_arr = np.array([1,-2,2,-76,44,-55,6,-43,-99,55])

n = len(my_arr)
    
pos = 0
for i in range(n):
    if my_arr[i]>=0:                
        pos+=1
neg = n - pos

#//--------------------------------------------------------------//

print(pivot(my_arr))
PosNeg(my_arr)


[  1   2  44   6  55 -55 -76 -43 -99  -2]
pos, negs are 5 5


array([  1, -76,  44, -99,  55, -55,   2, -43,   6,  -2])

#### Replace every array element by multiplication of previous and next

In [20]:
my_arr = np.array([1,   4,   3,   6,   8, 7, 5])

def RearrangeMulti(arr):
    n= len(arr)
    
    if n==1:
        return
    
    
    prev = arr[0]
    arr[0] = arr[0] * arr[1]
            
    for i in range(1,n-1):
            curr = arr[i]
            arr[i] = prev * arr[i+1]
            prev = curr
    arr[n-1] = prev*arr[n-1]
    
    return arr

RearrangeMulti(my_arr)
            

array([ 4,  3, 24, 24, 42, 40, 35])

#### Shuffle a given array using Fisher–Yates shuffle Algorithm

In [21]:
import random
#-----------------------#

my_arr = np.array([1,   4,   3,   6,   8, 7, 5, 10, 11, 12])

def randomize(arr):
    n = len(arr)
    
    for i in range(n-1):
        j = random.randint(i,n-1)
        
        arr[i],arr[j] = arr[j],arr[i]
        
    return arr

randomize(my_arr)

array([ 5, 10,  8,  7,  3,  1,  6, 12,  4, 11])

#### Method 1 : Segregate even and odd numbers 

In [54]:
array = np.array([ 100 ,3, 2, 4, 7, 6, 90, 10,5])

def segregate(arr):
    n = len(arr)
    
    even = 0
    for i in range(n):
        if arr[i]%2 ==0:
            even +=1
    odd = n-even
    
    print(even,odd)
    
    for k in range(0,even):
        temp = arr[k]
        for j in range(k,n):
            if arr[j]%2 == 0:
                print("Values of K and J are {} and {}".format(k,j))
                arr[j],arr[k] = arr[k],arr[j]
                break
    return arr       
    
    
segregate(array)

6 3
Values of K and J are 0 and 0
Values of K and J are 1 and 2
Values of K and J are 2 and 3
Values of K and J are 3 and 5
Values of K and J are 4 and 6
Values of K and J are 5 and 7


array([100,   2,   4,   6,  90,  10,   7,   3,   5])

#### Method 2 :  : Lomuto’s Partition Scheme

In [57]:
def arrayEvenAndOdd(arr):
    
    n = len(arr)
    
    i = -1
    j= 0
    while (j!=n):
        if (arr[j] % 2 ==0):
            i = i+1
 
            # Swapping even and odd numbers
            arr[i],arr[j] = arr[j],arr[i]
             
        j = j+1
    return arr

array = np.array([ 100 ,3, 2, 4, 7, 6, 90, 10,5])

arrayEvenAndOdd(array)

array([100,   2,   4,   6,  90,  10,   7,   3,   5])