#### K’th Smallest/Largest Element in Unsorted Array | Set 1

##### Method 1

In [1]:
import numpy as np

In [2]:

def KthElement(arr,p,k):
    n = len(arr)
    arr.sort()
    print("Sorted Array for manual check ",arr)
    if (p == 1 and k>0 and k<=n):
        return arr[k-1]
    elif (p == 2 and k>0 and k<=n):
        return print("Here is your answer {}".format(arr[n-k]))


my_Arr = np.array([7, 10, 4, 3, 20, 15])
n = len(my_Arr)    
p = int(input("you want Kth Smallest(type 1) or Kth Largest(type 2)? : "))    
k = int(input("which smallest/Largest value you want (1 = k <= {}) : ".format(n)))
    
KthElement(my_Arr,p,k)

you want Kth Smallest(type 1) or Kth Largest(type 2)? : 2
which smallest/Largest value you want (1 = k <= 6) : 5
Sorted Array for manual check  [ 3  4  7 10 15 20]
Here is your answer 4


##### Method 2

In [3]:

# This function returns k'th smallest element
# in arr[l..r] using QuickSort based method.
# ASSUMPTION: ALL ELEMENTS IN ARR[] ARE DISTINCT
import sys
 
def kthSmallest(arr, l, r, k):
 
    # If k is smaller than number of
    # elements in array
    if (k > 0 and k <= r - l + 1):
     
        # Partition the array around last
        # element and get position of pivot
        # element in sorted array
        pos = partition(arr, l, r)
 
        # If position is same as k
        if (pos - l == k - 1):
            return arr[pos]
        if (pos - l > k - 1): # If position is more,
                              # recur for left subarray
            return kthSmallest(arr, l, pos - 1, k)
 
        # Else recur for right subarray
        return kthSmallest(arr, pos + 1, r,
                            k - pos + l - 1)
 
    # If k is more than number of
    # elements in array
    return sys.maxsize
 
# Standard partition process of QuickSort().
# It considers the last element as pivot and
# moves all smaller element to left of it
# and greater elements to right
def partition(arr, l, r):
 
    x = arr[r]
    i = l
    for j in range(l, r):
        if (arr[j] <= x):
            arr[i], arr[j] = arr[j], arr[i]
            i += 1
    arr[i], arr[r] = arr[r], arr[i]
    return i

# Driver Code
if __name__ == "__main__":
     
    arr = [12, 3, 5, 7, 4, 19, 26]
    n = len(arr)
    k = 5;
    print("K'th smallest element is",
           kthSmallest(arr, 0, n - 1, k))

K'th smallest element is 12


#### K Smallest/Largest Element

In [4]:
def Kelements(arr,k):
    arr.sort()
    
    return print(arr[k+1:])

My_Arr =np.array([1, 23, 12, 9, 30, 2, 50])
Kelements(My_Arr,3)
    

[23 30 50]


#### Find all elements in array which have at-least two greater elements

In [5]:
#We can also do by sorting this array in simple way but lets look at this one

My_Arr =np.array([1, 23, 12, 9, 30, 2, 5])

def Elements2Greater(arr):
    n = len(arr)
    
    for i in range(n):
        count = 0
        for j in range(n):

            if arr[j]>arr[i]:
                count += 1
        if count >= 2:
            print(arr[i],end = " ")
    

Elements2Greater(My_Arr)

1 12 9 2 5 

#### Program for Mean and median of an unsorted array

In [6]:
Array = np.array([1, 3, 4, 2, 6, 5, 8, 7])

def Mean(arr):
    
    n = len(arr)
    sum = 0
    for i in range(n):
        sum = sum + arr[i]
    
    mean =float(sum/n)
    
    return mean

def Median(arr):
    n = len(arr)
    
    arr.sort()
    
    if n%2 !=0:
        return arr[int(n/2)+1]
    else:
        return (arr[int(n/2)-1]+arr[int(n/2)]) / 2



print("For the given array Mean is {} and Median is {} .".format(Mean(Array) , Median(Array)))


For the given array Mean is 4.5 and Median is 4.5 .


#### Median of Stream of Running Integers

In [7]:
def Inputs(arr,r):

    k=0
    while k<r:
        p = int(input("Enter the number : "))
        arr[0][k] = p
        k+=1
        
    if r==1:
        return arr[0][0]
    if r ==2:
        return (arr[0][0]+arr[0][1]) / 2
    
    else:
        for i in range(3,r+1):
            if r%2 !=0:
                return arr[0][int(r/2)]
            else:
                return (arr[0][int(r/2)-1]+arr[0][int(r/2)]) / 2
                
Array = np.zeros((1,2))
Inputs(Array,2)

Enter the number : 25
Enter the number : 25


25.0

#### Minimum product of k integers in an array of positive Integers

#### K-th Largest Sum Contiguous Subarray

In [8]:
My_Array = np.array([20, -15, 14, -5, -6, 1, 4])

def ContiguousSum(arr ,k):
    n = len(arr)
    
    arr1 = arr.copy()
    
    sum = 0
    for i in range(n):
        sum = sum + arr[i]
        arr1[i] = sum
    return print("Your {}th largest sum is {}".format(k, arr1[k]))

ContiguousSum(My_Array,6)

Your 6th largest sum is 13


#### Not the exact solution :: a try :: K maximum sum combinations from two arrays

In [9]:
#Only if K < Length of any one array. # also length of each array must be same.

arr1 = np.array([8, 0, 3, 5])
arr2 = np.array([4, 2, 5, 1])

def KmaxSum(arr1,arr2,k):
    n = len(arr1)
    
    arr1.sort()
    arr2.sort()
    
    for i in range(n-1,n-k-1,-1):
        sum = arr1[i] + arr2[n-1]
        print(sum, end = " ")

KmaxSum(arr1,arr2,4)



13 10 8 5 

#### K maximum sums of Non-overlapping contiguous sub-arrays

In [10]:
def KmaxSums(arr , k):
    n = len(arr)
    
    # In each iteration it will give
    # the ith maximum subarray sum.
    for x in range(k):
        
        # Kadane's algorithm
        max_so_far = -float("inf")
        max_here = 0
        
        #Determining the starting and ending indexes of a array for which sum is described
        start = 0
        end = 0
        s = 0
        
        for i in range(n):
            
            max_here += arr[i]
            
            if (max_so_far < max_here):
                
                max_so_far = max_here
                
                start  = s
                end = i
                
            if max_here < 0:
                max_here = 0
                s = i+1
            
        print("Max K sum is {} starting at index {} and ending at index {} ".format(max_so_far,start,end))
            
        for p in range(start ,end+1):
            arr[p] = -float(1e6)
    print()
    
array = np.array([4, 1, 1, -1, -3, -5, 6, 2, 6, -2])

KmaxSums(array,3)

Max K sum is 14 starting at index 6 and ending at index 8 
Max K sum is 6 starting at index 0 and ending at index 2 
Max K sum is -1 starting at index 3 and ending at index 3 



#### k smallest elements in same order using O(1) extra space

In [11]:
def Ksmallest(arr, n, k):

    for i in range(k, n):

        max_var = arr[k - 1]
        pos = k - 1
        
        for j in range(k - 2, -1, -1):
                     
            if (arr[j] > max_var):
             
                max_var = arr[j]
                pos = j

        if (max_var > arr[i]):
         
            j = pos
            while (j < k - 1):
             
                arr[j] = arr[j + 1]
                j += 1

            arr[k - 1] = arr[i]

    for i in range(0, k):
        print(arr[i], end = " ")

arr = [9, 5, 8, 0, 6, 7, 3, 4, 2, 1]
n = len(arr)
k = 5

Ksmallest(arr, n, k)

0 3 4 2 1 

#### Find k pairs with smallest sums in two arrays

In [12]:
import sys

def PairsSmallest(arr1,arr2,k):
    n1 = len(arr1)
    n2 = len(arr2)
    
    if k > n1*n1:
        print("K pairs doesn't exist")
        
    index_2 = [0 for i in range(n2)]
    
    while k>0:

        min_sum = sys.maxsize
        min_index = 0


        for i1 in range(n1):

            if (index_2[i1] < n2 and arr1[i1] + arr2[index_2[i1]] < min_sum):

                # Update index that gives minimum
                min_index = i1

                # update minimum sum
                min_sum = arr1[i1] + arr2[index_2[i1]]

        print((arr1[min_index] , arr2[index_2[min_index]]), end = " ")

        index_2[min_index] += 1

        k -= 1

    
arr1 = [1, 3, 11]
arr2 = [2, 4, 8]


PairsSmallest(arr1,arr2,6)

(1, 2) (1, 4) (3, 2) (3, 4) (1, 8) (3, 8) 

#### k-th smallest absolute difference of two elements in an array

In [13]:
arr = [1,4,2,7,9,5,6]



#### k-th smallest absolute difference of two elements in two arrays

In [14]:
def PairsSmallest(arr1,arr2,k):
    n1 = len(arr1)
    n2 = len(arr2)
    
    if k > n1*n1:
        print("K pairs doesn't exist")
        
    index_2 = [0 for i in range(n2)]
    
    while k>0:

        min_sum = sys.maxsize
        min_index = 0


        for i1 in range(n1):

            if (index_2[i1] < n2 and arr1[i1] + arr2[index_2[i1]] < min_sum):

                # Update index that gives minimum
                min_index = i1

                # update minimum sum
                min_sum = arr1[i1] + arr2[index_2[i1]]

        print(int(arr1[min_index] - arr2[index_2[min_index]]),  end = " ")

        index_2[min_index] += 1

        k -= 1

    
arr1 = [1, 3, 11]
arr2 = [2, 4, 8]


PairsSmallest(arr1,arr2,4)

-1 -3 1 -1 

#### Find Second largest element in an array

In [15]:
arr = np.array([ 5, 11, 0, 6, 3, 4, 2, 1])

def Largest2nd(arr):
    
    n = len(arr)
    
    for i in range(2):
        temp = arr[i]
        
        for j in range(i,n):
            if arr[j]>temp:
                temp = arr[j]
                arr[i],arr[j] = arr[j],arr[i]
        if i == 1:
            print("The second largest element of the array is : ",temp)
                    
Largest2nd(arr)

The second largest element of the array is :  6


#### Find k numbers with most occurrences in the given array

In [16]:
array_occ  = np.array([7, 10, 11, 5, 2, 5, 5, 7, 11, 8, 9, 7, 5])

def K_Num_Occur(arr,k):
    
    n = len(arr)
    
    std = 0
    for i in range(n-std):
        
        ln = len(arr)
        p = arr[i]
        
        print(n-std , ln)
        
        count = 0
        for j in range(ln-count):
            if j<n:
                if arr[j] == arr[i]:
                    count += 1
                    std += 1
        if count == 1:
            print(arr[i], "has the frequency of : 1")
            arr = arr[arr != p]
        print("count and std are: ",count,std)
                
        print(arr[i], "has the frequency of : ", count)
        arr = arr[arr != p]
        print(arr)   
        
        
        
K_Num_Occur(array_occ, 7)   

13 13
count and std are:  3 3
7 has the frequency of :  3
[10 11  5  2  5  5 11  8  9  5]
10 10
count and std are:  2 5
11 has the frequency of :  2
[10  5  2  5  5  8  9  5]
8 8
2 has the frequency of : 1
count and std are:  1 6
5 has the frequency of :  1
[10  5  5  5  8  9  5]
7 7
count and std are:  4 10
5 has the frequency of :  4
[10  8  9]


IndexError: index 4 is out of bounds for axis 0 with size 3

#### Find the smallest and second smallest elements in an array

In [18]:
def SmallestTwo(arr):
    
    n = len(arr)
    
    for i in range(2):
        temp = arr[i]
        
        for j in range(i,n):
            if arr[j]<temp:
                temp = arr[j]
                arr[i],arr[j] = arr[j],arr[i]
        if i <=1:
            print("The {}st Smallest element of the array is : {} ".format((i+1),temp))
            
arr = np.array([ 5, 11, 6, 3, 7])        

SmallestTwo(arr)

The 1st Smallest element of the array is : 3 
The 2st Smallest element of the array is : 5 


#### Find the smallest missing number

In [54]:
#This is for a sorted array ranging from 0 to m. where m is equal to max value available + 1.
 
def SmallMiss(arr,m):
    
    n = len(arr)
    
    for i in range(n-1):
        
        if arr[0]!=0:
            print("The smallest missing number for the given array is : ",0)
            break
            
        if arr[i+1] - arr[i]> 1:
            print("The smallest missing number for the given array is : ",arr[i]+1)
            break
            
        if i == n-2 :
            print("The smallest missing number for the given array is : ",arr[n-1] + 1)
            break
    
my_arr = np.array([0,1,2,3, 5,6,7,8])

#Since the array is in range of 0-11. Here our M value is 11. 
m =11

SmallMiss(my_arr, m)




The smallest missing number for the given array is :  4


#### Maximum sum such that no two elements are adjacent

#### Maximum and minimum of an array using minimum number of comparisons

In [69]:
array  = np.array([7, 18, 10, 5, 2, 6, 8, 11, 9])

def Smallest(arr):
    n = len(arr)
    
    temp = arr[0]
        
    for j in range(n):
        if arr[j]<temp:
            temp = arr[j]
    return temp


def Largest(arr):
    n = len(arr)
    
    temp1 = arr[0]
        
    for j in range(n):
        if arr[j]>temp1:
            temp1 = arr[j]
    return temp1

print("The smallest element is {} and Largest is {}".format(Smallest(array) , Largest(array)))

The smallest element is 2 and Largest is 18
