In [1]:
import numpy as np
import sys
import math

#### Alternative Sorting

In [2]:
myarr = np.array([7, 1, 2, 3, 4, 8, 5, 6])

def AlterSort(arr):
    n = len(arr)
    
    arr.sort()
    
    i= 0
    j = n-1
    
    while i<j:
        print(arr[j], end = " ")
        print(arr[i], end = " ")
        i+=1
        j-=1
        
AlterSort(myarr)

8 1 7 2 6 3 5 4 

#### Sort a nearly sorted (or K sorted) array


In [3]:
array = np.array([2, 6, 3, 12, 56, 8])

def Ksorted(A):
    n = len(A)
    
    for i in range(n):
        j = i-1
        key = A[i]

        while j>=0 and A[j]>key:
            A[j+1] = A[j]
            j = j-1
            A[j+1] = key
    return A

Ksorted(array)

array([ 2,  3,  6,  8, 12, 56])

#### Sort an array according to absolute difference with given value


In [4]:
ABS = np.array([2, 6, 8, 3])

def SortAbs(arr,x):
    n = len(arr)
    
    diff = [0]*n
    for i in range(n):
        diff[i] = abs(arr[i]-x)
        
    l=0
    indexes = [0]*n
    while l<n:
        key = diff.index(min(diff))
        diff[key] = float('inf')
        indexes[l] = key
        l+=1
        
    ans = arr.copy()
    for m in range(n):
        ans[m] = arr[indexes[m]]
    
    return ans

SortAbs(ABS,5)

array([6, 3, 2, 8])

#### Sort an array in wave form


In [5]:
WF = np.array([10, 90, 49, 2, 1, 5, 23])

def WaveSorted(arr):
    n = len(arr)
    
    for i in range(0,n,2):
        
        if (i>0 and arr[i] < arr[i-1]):
            arr[i],arr[i-1] = arr[i-1],arr[i]
        
        if (i<n-1 and arr[i] < arr[i+1]):
            arr[i],arr[i+1] = arr[i+1],arr[i]
    return arr
    
WaveSorted(WF)

array([90, 10, 49,  1,  5,  2, 23])

#### Merge an array of size n into another array of size m+n


In [6]:
NA = -1

MpN = np.array([2, 8, NA, NA, NA, 13, NA, 15, 20])
N = np.array([5, 7, 9, 25])

def MplusN(MN,N):
    
    mn = len(MN)
    n = len(N)
    
    for i in range(n):
        for j in range(mn):
            if (MN[j] == -1):
                MN[j] = N[i]
                break
    MN.sort()
    return MN

MplusN(MpN,N)


array([ 2,  5,  7,  8,  9, 13, 15, 20, 25])

#### Sort an array which contain 1 to n values


In [7]:
SrtArr = np.array([10, 7, 9, 2, 8, 3, 5, 4, 6, 1])

n = len(SrtArr)
for i in range(n):
    SrtArr[i] = i+1
    
print(SrtArr)

[ 1  2  3  4  5  6  7  8  9 10]


#### Sort elements by frequency | Set 1


In [8]:

#//----------------Brute Force Method-------------------//

Freq = np.array([2, 5,-1, 2, 6, -1, 9999999, 5, 8, 8, 8])

def SortFreq(arr):
    n = len(arr)
    
    arr.sort()
    
    dc = {}
    for i in range(n):
        temp = arr[i]
        count = 0
        for j in range(n):
            if arr[j] == temp:
                count += 1
        dc[temp] = count
        
    sorte = dict(sorted(dc.items(), key=lambda item: item[1], reverse = True))
    k = list(sorte.keys())
    
    print("Array sorted by frequency is : ", end= " ")
    for p,s in enumerate(k):
        l = sorte[s] 
        for s in range(l):
            print(k[p], end = " " )

SortFreq(Freq)

Array sorted by frequency is :  8 8 8 -1 -1 2 2 5 5 6 9999999 

#### Count Inversions in an array | Set 1 (Using Merge Sort)

In [9]:
Inv = np.array([1, 20, 6, 4, 5])

def Inversions(arr):
    n = len(arr)
    count = 0
    for i in range(n):
        temp = arr[i]
        for j in range(i+1,n):
            if arr[j] < temp:
                count += 1
    return count

Inversions(Inv)

5

#### Two elements whose sum is closest to zero

In [10]:
CLZ = np.array([1, -9, 10, 7, -80, 8])

def NearZero(arr):
    n = len(arr)
    
    arr.sort()
    i = 0
    j = n-1
    
    aux = 9999999
    
    while (i < j):

        temp = arr[i]+arr[j]
        
        if abs(temp) < aux:
            aux = abs(temp)
            p =i
            k=j
            
        if temp == 0:
            return i,j,arr
        
        else:
            if temp<0:
                i+=1
            if temp>0:
                j-=1
                
  
    print(arr)
    return print("The min distance found from 0 is {} with pair {},{}".format(aux,arr[p],arr[k]))

NearZero(CLZ)

[-80  -9   1   7   8  10]
The min distance found from 0 is 1 with pair -9,10


#### Minimum number of swaps required to sort an array


In [11]:
Swap = np.array([101, 758, 315, 730, 472, 619, 460, 479 ])

def minSwap(arr):
    n = len(arr)
    
    ans = 0
    temp = arr.copy()
    h = {}
    temp.sort()
 
    for i in range(n):
        h[arr[i]] = i
         
    init = 0
    for i in range(n):
        if (arr[i] != temp[i]):
            ans += 1
            init = arr[i]

            arr[i], arr[h[temp[i]]] = arr[h[temp[i]]], arr[i]
 
            h[init] = h[temp[i]]
            h[temp[i]] = i
    return print("Min swaps required are : ",ans)
minSwap(Swap)

Min swaps required are :  5


#### Union and Intersection of two sorted arrays


In [12]:
arr1 = [2, 2, 4, 6, 7, 8]
arr2 = [1, 2, 2, 3, 4]

def Union(arr1,arr2):
    n1 = len(arr1)
    n2 = len(arr2)
    
    for i in range(n2):
        if arr2[i] not in arr1:
            arr1.append(arr2[i])
    arr1.sort()
    return print("Union is : ",arr1)


Union(arr1,arr2)

Union is :  [1, 2, 2, 3, 4, 6, 7, 8]


In [13]:
a1 = [4, 2, 7,9, 6, 8]
a2 = [1, 2, 7, 3, 4]

def Intersection(arr1,arr2):
    n1 = len(arr1)
    n2 = len(arr2)
    In = []
    for i in range(n2):
        if arr2[i] in arr1:
            In.append(arr2[i])
    return print("Intersection is : ",In)
Intersection(a1,a2)

Intersection is :  [2, 7, 4]


#### Sort an array of 0s, 1s and 2s

In [14]:
A210r = np.array([0, 1, 1, 2, 1, 2, 1, 2, 0, 1, 0, 1])

def Sort210(arr):
    n = len(arr)
    
    l = 0
    m = 0
    h = n-1
    
    
    while m<=h:
        
        if arr[m] == 0:
            arr[l],arr[m] = arr[m],arr[l]
            l += 1
            m+=1
            
        elif arr[m] == 1:
            m += 1
        else:
            arr[m],arr[h] = arr[h],arr[m]
            h -= 1
    return arr

Sort210(A210r)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2])

#### Find the Minimum length Unsorted Subarray, sorting which makes the complete array sorted


In [15]:
CSRT = np.array([0, 1, 15, 25, 6, 7, 30, 40, 50])

def CandSort(arr):
    n = len(arr)
    
    for i in range(n):
        if arr[i]>arr[i+1]:
            s = i
            break
    for j in range(n-1,0,-1):
        if arr[j]<arr[j-1]:
            e = j
            break
            
    arr[i:j+1].sort()

    count = 0
    for p in range(n-1):
        if arr[p]<arr[p+1]:
            count +=1

    if count == n:
        return s,e
    else:
        minval = min(arr[s:e+1])
        maxval = max(arr[s:e+1])

        for l in range(s+1):
            if arr[l] > minval:
                s = l
                break
        for m in range(e+1,n):
            if arr[m] < maxval:
                e = m
                break
    return print("The range for smallest array required to be sorted to sort to complete array is :",s," to ",e)
CandSort(CSRT)

The range for smallest array required to be sorted to sort to complete array is : 2  to  5


#### Count the number of possible triangles


In [16]:
Tri_Arr = np.array([ 10, 21, 22, 100, 101, 200, 300 ])

def Triangles(arr):
    count = 0
    n = len(arr)
    
    for i in range(n):
        for j in range(i+1, n):
            for k in range(j+1, n):
                if (arr[i] + arr[j] > arr[k] and 
                    arr[i] + arr[k] > arr[j] and 
                    arr[k] + arr[j] > arr[i]):
                    
                    count += 1
    
    return print("Total Triangles can be made from the given array are : ",count)

Triangles(Tri_Arr)
    

Total Triangles can be made from the given array are :  6


#### Find number of pairs (x, y) in an array such that x^y > y^x


In [17]:
def countPairsBruteForce(X, Y, m, n):
    ans = 0
    for i in range(m):
        for j in range(n):
            if (pow(X[i], Y[j]) > pow(Y[j], X[i])):
                ans += 1
    return ans

X = (10, 19, 18)
Y = (11, 15, 9)

countPairsBruteForce(X,Y,len(X),len(Y))

2

#### Print All Distinct Elements of a given integer array


In [21]:
Distinct = np.array([30, 10, 21, 30, 22, 10, 11, 10, 20, 30, 21, 30, 10])

def Distincts(arr):
    list = []
    for i in range(n):
        if arr[i] not in list:
            list.append(arr[i])
    return list

Distincts(Distinct)

[30, 10, 21, 22, 11, 20]

#### Construct an array from its pair - sum array


In [53]:
Pairs = np.array([15, 13, 11, 10, 12, 10, 9, 8, 7, 5])

#So, if the length of a array is n then in the pair array we will have n(n-1)/2 elements 
#by simple airthmatic



def FindArr(pair):
    n = len(pair)
    
    #Finding the len of original array
    l = (1 + (1 + (4 * 2*(n)))**0.5)/2
    
    Array = [0]*int(l)
    
    Array[0] = (pair[0]+pair[1] - pair[int(l)-1]) // 2
    
    for i in range(1,int(l)):
        Array[i] = pair[i-1]-Array[0]
 
    print (Array)
FindArr(Pairs)
    

[8, 7, 5, 3, 2]


#### Merge two sorted arrays with O(1) extra space

![Image](https://media.geeksforgeeks.org/wp-content/cdn-uploads/Merge-two-sorted-Arrays.png)

In [57]:
def MergeSortSA(arr1,arr2):
    n1 = len(arr1)
    n2 = len(arr2)
    
    for i in range(n2-1,0,-1):
        last = arr1[n1-1]
        
        j = n1-2
        while(j >= 0 and arr1[j] > arr2[i]):
            arr1[j+1] = arr1[j]
            j-=1
  
        # If there was a greater element
        if (j != n1-2 or last > arr2[i]):
         
            arr1[j+1] = arr2[i]
            arr2[i] = last
            
    return arr1, arr2    

Arr1 = [1, 5, 9, 10, 15, 20]
Arr2 = [2, 3, 8, 13]
MergeSortSA(Arr1, Arr2)

([1, 3, 5, 8, 9, 10], [2, 13, 15, 20])

#### Product of maximum in first array and minimum in second


In [69]:
def minMaxProduct(arr1, arr2, n1, n2) :
    maxval = arr1[0]
    minval  = arr2[0]
    
    i = 0
    while (i < n1) :
     
        if (arr1[i] > maxval) :
            maxval = arr1[i]
        i += 1
        
    j = 0 
    while (j < n2):
     
        if (arr2[j] < minval) :
            minval = arr2[j]
        j += 1
 
    return maxval * minval

arr1 = [10, 2, 3, 6, 4, 1 ]
arr2 = [5, 1, 4, 6, 7, 9 ]
n1 = len(arr1)
n2 = len(arr1)
print(minMaxProduct(arr1, arr2, n1, n2))

10
